/*
* generated by Xtext
*/
package dk.itu.smdp.group11.survey.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SurveyAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("dk/itu/smdp/group11/survey/parser/antlr/internal/InternalSurvey.tokens");
	}
}
