/**
 * generated by Xtext
 */
package dk.itu.smdp.group11.survey.serializer;

import dk.itu.smdp.group11.survey.serializer.AbstractSurveySyntacticSequencer;

@SuppressWarnings("all")
public class SurveySyntacticSequencer extends AbstractSurveySyntacticSequencer {
}
