/**
 * generated by Xtext
 */
package dk.itu.smdp.group11.survey.serializer;

import dk.itu.smdp.group11.survey.serializer.AbstractSurveySemanticSequencer;

@SuppressWarnings("all")
public class SurveySemanticSequencer extends AbstractSurveySemanticSequencer {
}
