/**
 * generated by Xtext
 */
package dk.itu.smdp.group11.survey.ui.contentassist;

import dk.itu.smdp.group11.survey.ui.contentassist.AbstractSurveyProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SurveyProposalProvider extends AbstractSurveyProposalProvider {
}
