/*
* generated by Xtext
*/
package dk.itu.smdp.group11.survey.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class SurveyGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class SurveyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Survey");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSurveyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIntroKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIntroAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIntroEStringParserRuleCall_2_1_0 = (RuleCall)cIntroAssignment_2_1.eContents().get(0);
		private final Assignment cQuestionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cQuestionsQuestionParserRuleCall_3_0 = (RuleCall)cQuestionsAssignment_3.eContents().get(0);
		private final Assignment cQuestionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cQuestionsQuestionParserRuleCall_4_0 = (RuleCall)cQuestionsAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOutroKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cOutroAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cOutroEStringParserRuleCall_5_1_0 = (RuleCall)cOutroAssignment_5_1.eContents().get(0);
		
		//Survey:
		//	"Survey" name=EString ("Intro" intro=EString)? questions+=Question questions+=Question* ("Outro" outro=EString)?;
		public ParserRule getRule() { return rule; }

		//"Survey" name=EString ("Intro" intro=EString)? questions+=Question questions+=Question* ("Outro" outro=EString)?
		public Group getGroup() { return cGroup; }

		//"Survey"
		public Keyword getSurveyKeyword_0() { return cSurveyKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//("Intro" intro=EString)?
		public Group getGroup_2() { return cGroup_2; }

		//"Intro"
		public Keyword getIntroKeyword_2_0() { return cIntroKeyword_2_0; }

		//intro=EString
		public Assignment getIntroAssignment_2_1() { return cIntroAssignment_2_1; }

		//EString
		public RuleCall getIntroEStringParserRuleCall_2_1_0() { return cIntroEStringParserRuleCall_2_1_0; }

		//questions+=Question
		public Assignment getQuestionsAssignment_3() { return cQuestionsAssignment_3; }

		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_3_0() { return cQuestionsQuestionParserRuleCall_3_0; }

		//questions+=Question*
		public Assignment getQuestionsAssignment_4() { return cQuestionsAssignment_4; }

		//Question
		public RuleCall getQuestionsQuestionParserRuleCall_4_0() { return cQuestionsQuestionParserRuleCall_4_0; }

		//("Outro" outro=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"Outro"
		public Keyword getOutroKeyword_5_0() { return cOutroKeyword_5_0; }

		//outro=EString
		public Assignment getOutroAssignment_5_1() { return cOutroAssignment_5_1; }

		//EString
		public RuleCall getOutroEStringParserRuleCall_5_1_0() { return cOutroEStringParserRuleCall_5_1_0; }
	}

	public class QuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Question");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cQuestion_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTableQuestionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Question:
		//	Question_Impl | TableQuestion;
		public ParserRule getRule() { return rule; }

		//Question_Impl | TableQuestion
		public Alternatives getAlternatives() { return cAlternatives; }

		//Question_Impl
		public RuleCall getQuestion_ImplParserRuleCall_0() { return cQuestion_ImplParserRuleCall_0; }

		//TableQuestion
		public RuleCall getTableQuestionParserRuleCall_1() { return cTableQuestionParserRuleCall_1; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class Question_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Question_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cQuestionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Assignment cIsExclusiveAssignment_2_0 = (Assignment)cUnorderedGroup_2.eContents().get(0);
		private final Keyword cIsExclusiveExclusiveKeyword_2_0_0 = (Keyword)cIsExclusiveAssignment_2_0.eContents().get(0);
		private final Assignment cIsOptionalAssignment_2_1 = (Assignment)cUnorderedGroup_2.eContents().get(1);
		private final Keyword cIsOptionalOptionalKeyword_2_1_0 = (Keyword)cIsOptionalAssignment_2_1.eContents().get(0);
		private final Assignment cBodyAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBodyEStringParserRuleCall_3_0 = (RuleCall)cBodyAssignment_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cAnswersAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cAnswersAnswerParserRuleCall_5_0 = (RuleCall)cAnswersAssignment_5.eContents().get(0);
		private final Assignment cAnswersAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cAnswersAnswerParserRuleCall_6_0 = (RuleCall)cAnswersAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Question_Impl returns Question:
		//	"Question" name=ID (isExclusive?="exclusive"? & isOptional?="optional"?) body=EString "(" answers+=Answer
		//	answers+=Answer* ")";
		public ParserRule getRule() { return rule; }

		//"Question" name=ID (isExclusive?="exclusive"? & isOptional?="optional"?) body=EString "(" answers+=Answer
		//answers+=Answer* ")"
		public Group getGroup() { return cGroup; }

		//"Question"
		public Keyword getQuestionKeyword_0() { return cQuestionKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//isExclusive?="exclusive"? & isOptional?="optional"?
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }

		//isExclusive?="exclusive"?
		public Assignment getIsExclusiveAssignment_2_0() { return cIsExclusiveAssignment_2_0; }

		//"exclusive"
		public Keyword getIsExclusiveExclusiveKeyword_2_0_0() { return cIsExclusiveExclusiveKeyword_2_0_0; }

		//isOptional?="optional"?
		public Assignment getIsOptionalAssignment_2_1() { return cIsOptionalAssignment_2_1; }

		//"optional"
		public Keyword getIsOptionalOptionalKeyword_2_1_0() { return cIsOptionalOptionalKeyword_2_1_0; }

		//body=EString
		public Assignment getBodyAssignment_3() { return cBodyAssignment_3; }

		//EString
		public RuleCall getBodyEStringParserRuleCall_3_0() { return cBodyEStringParserRuleCall_3_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }

		//answers+=Answer
		public Assignment getAnswersAssignment_5() { return cAnswersAssignment_5; }

		//Answer
		public RuleCall getAnswersAnswerParserRuleCall_5_0() { return cAnswersAnswerParserRuleCall_5_0; }

		//answers+=Answer*
		public Assignment getAnswersAssignment_6() { return cAnswersAssignment_6; }

		//Answer
		public RuleCall getAnswersAnswerParserRuleCall_6_0() { return cAnswersAnswerParserRuleCall_6_0; }

		//")"
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
	}

	public class AnswerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Answer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAnswerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIsFreeTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cIsFreeTextFreetextKeyword_1_0 = (Keyword)cIsFreeTextAssignment_1.eContents().get(0);
		private final Assignment cBodyAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cBodyEStringParserRuleCall_2_0 = (RuleCall)cBodyAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cFollowupAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cFollowupQuestionCrossReference_3_1_0 = (CrossReference)cFollowupAssignment_3_1.eContents().get(0);
		private final RuleCall cFollowupQuestionEStringParserRuleCall_3_1_0_1 = (RuleCall)cFollowupQuestionCrossReference_3_1_0.eContents().get(1);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cCommaKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cFollowupAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final CrossReference cFollowupQuestionCrossReference_3_2_1_0 = (CrossReference)cFollowupAssignment_3_2_1.eContents().get(0);
		private final RuleCall cFollowupQuestionEStringParserRuleCall_3_2_1_0_1 = (RuleCall)cFollowupQuestionCrossReference_3_2_1_0.eContents().get(1);
		
		//Answer:
		//	"Answer" isFreeText?="freetext"? body=EString ("->" followup+=[Question|EString] (","
		//	followup+=[Question|EString])*)?;
		public ParserRule getRule() { return rule; }

		//"Answer" isFreeText?="freetext"? body=EString ("->" followup+=[Question|EString] ("," followup+=[Question|EString])*)?
		public Group getGroup() { return cGroup; }

		//"Answer"
		public Keyword getAnswerKeyword_0() { return cAnswerKeyword_0; }

		//isFreeText?="freetext"?
		public Assignment getIsFreeTextAssignment_1() { return cIsFreeTextAssignment_1; }

		//"freetext"
		public Keyword getIsFreeTextFreetextKeyword_1_0() { return cIsFreeTextFreetextKeyword_1_0; }

		//body=EString
		public Assignment getBodyAssignment_2() { return cBodyAssignment_2; }

		//EString
		public RuleCall getBodyEStringParserRuleCall_2_0() { return cBodyEStringParserRuleCall_2_0; }

		//("->" followup+=[Question|EString] ("," followup+=[Question|EString])*)?
		public Group getGroup_3() { return cGroup_3; }

		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_3_0() { return cHyphenMinusGreaterThanSignKeyword_3_0; }

		//followup+=[Question|EString]
		public Assignment getFollowupAssignment_3_1() { return cFollowupAssignment_3_1; }

		//[Question|EString]
		public CrossReference getFollowupQuestionCrossReference_3_1_0() { return cFollowupQuestionCrossReference_3_1_0; }

		//EString
		public RuleCall getFollowupQuestionEStringParserRuleCall_3_1_0_1() { return cFollowupQuestionEStringParserRuleCall_3_1_0_1; }

		//("," followup+=[Question|EString])*
		public Group getGroup_3_2() { return cGroup_3_2; }

		//","
		public Keyword getCommaKeyword_3_2_0() { return cCommaKeyword_3_2_0; }

		//followup+=[Question|EString]
		public Assignment getFollowupAssignment_3_2_1() { return cFollowupAssignment_3_2_1; }

		//[Question|EString]
		public CrossReference getFollowupQuestionCrossReference_3_2_1_0() { return cFollowupQuestionCrossReference_3_2_1_0; }

		//EString
		public RuleCall getFollowupQuestionEStringParserRuleCall_3_2_1_0_1() { return cFollowupQuestionEStringParserRuleCall_3_2_1_0_1; }
	}

	public class TableQuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TableQuestion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTableQuestionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Assignment cIsExclusiveAssignment_2_0 = (Assignment)cUnorderedGroup_2.eContents().get(0);
		private final Keyword cIsExclusiveExclusiveKeyword_2_0_0 = (Keyword)cIsExclusiveAssignment_2_0.eContents().get(0);
		private final Assignment cIsOptionalAssignment_2_1 = (Assignment)cUnorderedGroup_2.eContents().get(1);
		private final Keyword cIsOptionalOptionalKeyword_2_1_0 = (Keyword)cIsOptionalAssignment_2_1.eContents().get(0);
		private final Assignment cBodyAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBodyEStringParserRuleCall_3_0 = (RuleCall)cBodyAssignment_3.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cItemsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cItemsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cItemsItemParserRuleCall_7_0 = (RuleCall)cItemsAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cItemsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cItemsItemParserRuleCall_8_1_0 = (RuleCall)cItemsAssignment_8_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cAnswersAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cAnswersAnswerParserRuleCall_10_0 = (RuleCall)cAnswersAssignment_10.eContents().get(0);
		private final Assignment cAnswersAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cAnswersAnswerParserRuleCall_11_0 = (RuleCall)cAnswersAssignment_11.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//TableQuestion:
		//	"TableQuestion" name=ID (isExclusive?="exclusive"? & isOptional?="optional"?) body=EString "(" "Items" "("
		//	items+=Item ("," items+=Item)* ")" answers+=Answer answers+=Answer* ")";
		public ParserRule getRule() { return rule; }

		//"TableQuestion" name=ID (isExclusive?="exclusive"? & isOptional?="optional"?) body=EString "(" "Items" "(" items+=Item
		//("," items+=Item)* ")" answers+=Answer answers+=Answer* ")"
		public Group getGroup() { return cGroup; }

		//"TableQuestion"
		public Keyword getTableQuestionKeyword_0() { return cTableQuestionKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//isExclusive?="exclusive"? & isOptional?="optional"?
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }

		//isExclusive?="exclusive"?
		public Assignment getIsExclusiveAssignment_2_0() { return cIsExclusiveAssignment_2_0; }

		//"exclusive"
		public Keyword getIsExclusiveExclusiveKeyword_2_0_0() { return cIsExclusiveExclusiveKeyword_2_0_0; }

		//isOptional?="optional"?
		public Assignment getIsOptionalAssignment_2_1() { return cIsOptionalAssignment_2_1; }

		//"optional"
		public Keyword getIsOptionalOptionalKeyword_2_1_0() { return cIsOptionalOptionalKeyword_2_1_0; }

		//body=EString
		public Assignment getBodyAssignment_3() { return cBodyAssignment_3; }

		//EString
		public RuleCall getBodyEStringParserRuleCall_3_0() { return cBodyEStringParserRuleCall_3_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }

		//"Items"
		public Keyword getItemsKeyword_5() { return cItemsKeyword_5; }

		//"("
		public Keyword getLeftParenthesisKeyword_6() { return cLeftParenthesisKeyword_6; }

		//items+=Item
		public Assignment getItemsAssignment_7() { return cItemsAssignment_7; }

		//Item
		public RuleCall getItemsItemParserRuleCall_7_0() { return cItemsItemParserRuleCall_7_0; }

		//("," items+=Item)*
		public Group getGroup_8() { return cGroup_8; }

		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }

		//items+=Item
		public Assignment getItemsAssignment_8_1() { return cItemsAssignment_8_1; }

		//Item
		public RuleCall getItemsItemParserRuleCall_8_1_0() { return cItemsItemParserRuleCall_8_1_0; }

		//")"
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }

		//answers+=Answer
		public Assignment getAnswersAssignment_10() { return cAnswersAssignment_10; }

		//Answer
		public RuleCall getAnswersAnswerParserRuleCall_10_0() { return cAnswersAnswerParserRuleCall_10_0; }

		//answers+=Answer*
		public Assignment getAnswersAssignment_11() { return cAnswersAssignment_11; }

		//Answer
		public RuleCall getAnswersAnswerParserRuleCall_11_0() { return cAnswersAnswerParserRuleCall_11_0; }

		//")"
		public Keyword getRightParenthesisKeyword_12() { return cRightParenthesisKeyword_12; }
	}

	public class ItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Item");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsFreeTextAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsFreeTextFreetextKeyword_0_0 = (Keyword)cIsFreeTextAssignment_0.eContents().get(0);
		private final Assignment cBodyAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cBodyEStringParserRuleCall_1_0 = (RuleCall)cBodyAssignment_1.eContents().get(0);
		
		//Item:
		//	isFreeText?="freetext"? body=EString;
		public ParserRule getRule() { return rule; }

		//isFreeText?="freetext"? body=EString
		public Group getGroup() { return cGroup; }

		//isFreeText?="freetext"?
		public Assignment getIsFreeTextAssignment_0() { return cIsFreeTextAssignment_0; }

		//"freetext"
		public Keyword getIsFreeTextFreetextKeyword_0_0() { return cIsFreeTextFreetextKeyword_0_0; }

		//body=EString
		public Assignment getBodyAssignment_1() { return cBodyAssignment_1; }

		//EString
		public RuleCall getBodyEStringParserRuleCall_1_0() { return cBodyEStringParserRuleCall_1_0; }
	}
	
	
	private SurveyElements pSurvey;
	private QuestionElements pQuestion;
	private EStringElements pEString;
	private Question_ImplElements pQuestion_Impl;
	private AnswerElements pAnswer;
	private TableQuestionElements pTableQuestion;
	private ItemElements pItem;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public SurveyGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("dk.itu.smdp.group11.survey.Survey".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Survey:
	//	"Survey" name=EString ("Intro" intro=EString)? questions+=Question questions+=Question* ("Outro" outro=EString)?;
	public SurveyElements getSurveyAccess() {
		return (pSurvey != null) ? pSurvey : (pSurvey = new SurveyElements());
	}
	
	public ParserRule getSurveyRule() {
		return getSurveyAccess().getRule();
	}

	//Question:
	//	Question_Impl | TableQuestion;
	public QuestionElements getQuestionAccess() {
		return (pQuestion != null) ? pQuestion : (pQuestion = new QuestionElements());
	}
	
	public ParserRule getQuestionRule() {
		return getQuestionAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//Question_Impl returns Question:
	//	"Question" name=ID (isExclusive?="exclusive"? & isOptional?="optional"?) body=EString "(" answers+=Answer
	//	answers+=Answer* ")";
	public Question_ImplElements getQuestion_ImplAccess() {
		return (pQuestion_Impl != null) ? pQuestion_Impl : (pQuestion_Impl = new Question_ImplElements());
	}
	
	public ParserRule getQuestion_ImplRule() {
		return getQuestion_ImplAccess().getRule();
	}

	//Answer:
	//	"Answer" isFreeText?="freetext"? body=EString ("->" followup+=[Question|EString] (","
	//	followup+=[Question|EString])*)?;
	public AnswerElements getAnswerAccess() {
		return (pAnswer != null) ? pAnswer : (pAnswer = new AnswerElements());
	}
	
	public ParserRule getAnswerRule() {
		return getAnswerAccess().getRule();
	}

	//TableQuestion:
	//	"TableQuestion" name=ID (isExclusive?="exclusive"? & isOptional?="optional"?) body=EString "(" "Items" "("
	//	items+=Item ("," items+=Item)* ")" answers+=Answer answers+=Answer* ")";
	public TableQuestionElements getTableQuestionAccess() {
		return (pTableQuestion != null) ? pTableQuestion : (pTableQuestion = new TableQuestionElements());
	}
	
	public ParserRule getTableQuestionRule() {
		return getTableQuestionAccess().getRule();
	}

	//Item:
	//	isFreeText?="freetext"? body=EString;
	public ItemElements getItemAccess() {
		return (pItem != null) ? pItem : (pItem = new ItemElements());
	}
	
	public ParserRule getItemRule() {
		return getItemAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
