/*
* generated by Xtext
*/
package dk.itu.smdp.group11;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SurveyUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return dk.itu.smdp.group11.ui.internal.SurveyActivator.getInstance().getInjector("dk.itu.smdp.group11.Survey");
	}
	
}
