/*
* generated by Xtext
*/
package dk.itu.smdp.group11.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import dk.itu.smdp.group11.services.SurveyGrammarAccess;

public class SurveyParser extends AbstractContentAssistParser {
	
	@Inject
	private SurveyGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected dk.itu.smdp.group11.ui.contentassist.antlr.internal.InternalSurveyParser createParser() {
		dk.itu.smdp.group11.ui.contentassist.antlr.internal.InternalSurveyParser result = new dk.itu.smdp.group11.ui.contentassist.antlr.internal.InternalSurveyParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSurveyAccess().getAlternatives_1(), "rule__Survey__Alternatives_1");
					put(grammarAccess.getSurveyAccess().getAlternatives_5(), "rule__Survey__Alternatives_5");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getSurveyAccess().getGroup(), "rule__Survey__Group__0");
					put(grammarAccess.getQuestionAccess().getGroup(), "rule__Question__Group__0");
					put(grammarAccess.getContentAccess().getGroup(), "rule__Content__Group__0");
					put(grammarAccess.getAnswerAccess().getGroup(), "rule__Answer__Group__0");
					put(grammarAccess.getAnswerAccess().getGroup_1(), "rule__Answer__Group_1__0");
					put(grammarAccess.getAnswerAccess().getGroup_3(), "rule__Answer__Group_3__0");
					put(grammarAccess.getSurveyAccess().getIntroAssignment_2(), "rule__Survey__IntroAssignment_2");
					put(grammarAccess.getSurveyAccess().getQuestionsAssignment_3(), "rule__Survey__QuestionsAssignment_3");
					put(grammarAccess.getSurveyAccess().getQuestionsAssignment_4(), "rule__Survey__QuestionsAssignment_4");
					put(grammarAccess.getSurveyAccess().getOutroAssignment_6(), "rule__Survey__OutroAssignment_6");
					put(grammarAccess.getQuestionAccess().getIsExclusiveAssignment_1(), "rule__Question__IsExclusiveAssignment_1");
					put(grammarAccess.getQuestionAccess().getIsOptionalAssignment_2(), "rule__Question__IsOptionalAssignment_2");
					put(grammarAccess.getQuestionAccess().getContentAssignment_3(), "rule__Question__ContentAssignment_3");
					put(grammarAccess.getQuestionAccess().getAnswersAssignment_5(), "rule__Question__AnswersAssignment_5");
					put(grammarAccess.getQuestionAccess().getAnswersAssignment_6(), "rule__Question__AnswersAssignment_6");
					put(grammarAccess.getContentAccess().getBodyAssignment_1(), "rule__Content__BodyAssignment_1");
					put(grammarAccess.getAnswerAccess().getIsFreeTextAssignment_1_1(), "rule__Answer__IsFreeTextAssignment_1_1");
					put(grammarAccess.getAnswerAccess().getContentAssignment_2(), "rule__Answer__ContentAssignment_2");
					put(grammarAccess.getAnswerAccess().getFollowupAssignment_3_1(), "rule__Answer__FollowupAssignment_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			dk.itu.smdp.group11.ui.contentassist.antlr.internal.InternalSurveyParser typedParser = (dk.itu.smdp.group11.ui.contentassist.antlr.internal.InternalSurveyParser) parser;
			typedParser.entryRuleSurvey();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SurveyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SurveyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
