/*
 * generated by Xtext
 */
package dk.itu.smdp.group11.ui.contentassist

import dk.itu.smdp.group11.ui.contentassist.AbstractSurveyProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SurveyProposalProvider extends AbstractSurveyProposalProvider {
}
