/*
* generated by Xtext
*/
package dk.itu.smdp.group11;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SurveyStandaloneSetup extends SurveyStandaloneSetupGenerated{

	public static void doSetup() {
		new SurveyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

