/*
 * generated by Xtext
 */
package dk.itu.smdp.group11.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SurveyUiModule extends dk.itu.smdp.group11.ui.AbstractSurveyUiModule {
	public SurveyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
